### ISSUE TITLE
Add API URL in Swagger UI

### ISSUE THREAD

**Issue by Nikhil-Sarwara** [EventBurst/shiny-barnacle#23]
add the api url details in Swagger yaml file.

- [x] Agenda API Routes #24 
- [x] Speaker API Routes #26 
- [x] Session API Routes #28 
- [x] Event API Routes #29 
- [x] Sponsor API Routes #25 

This is in addition to #19
